[tool.poetry]
name = "vulcan-soa-connectathon-37"
version = "0.1.0"
description = ""
authors = ["Geoff Low <glow@mdsol.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
